#!/bin/bash

#if no argument is passed
if [ -z $1 ]; then

	#saves screenshot of entire screen to ~/Pictures/screencap with (Unix Timestamp)-full as the filename
	scrot ~/Pictures/screencap/%s-full.png
	
	#most recently modified file (screenshot we just made)
	lastSaved=$(ls ~/Pictures/screencap -t | head -n1)
	#sends a notification		
	notify-send 'Full screencap taken' 'Copied to clipboard and file saved to ~/Pictures/screencap/'${lastSaved}'.'

	#copies the image to clipboard (comment this out if you don't want that)
	xclip -selection clipboard -target image/png -i ~/Pictures/screencap/$lastSaved

#-r for region	
elif [ $1 = "-r" ]; then
	scrot -s -f ~/Pictures/screencap/%s-region.png
	if [ $? -eq 0 ]; then
		lastSaved=$(ls ~/Pictures/screencap -t | head -n1)
		notify-send 'Region screencap taken' 'Copied to clipboard and file saved to ~/Pictures/screencap/'${lastSaved}'.'
		xclip -selection clipboard -target image/png -i ~/Pictures/screencap/$lastSaved
	else
		notify-send 'Screencap cancelled.'
	fi

#-a for active window	
elif [ $1 = "-a" ]; then
	scrot -u ~/Pictures/screencap/%s-win.png
	lastSaved=$(ls ~/Pictures/screencap -t | head -n1)
	notify-send 'Window screencap taken' 'Copied to clipboard and file saved to ~/Pictures/screencap/'${lastSaved}'.'
	xclip -selection clipboard -target image/png -i ~/Pictures/screencap/$lastSaved

#won't see this if used as intended lol
else
	echo "Invalid option."
fi
